spring:
  application:
    name: api-gateway

# Define the port where the API gateway server would be running
server:
  port: ${SERVICE_PORT:9009}
  #port: 9009

zuul:
  routes:
    birthdays:
      sensitiveHeaders:
      path: /birthdays/**
      stripPrefix: true
      url: http://localhost:9090/birthdays
      #url: http://birthdays:9090
  #????
  add-proxy-headers: true

security:
  # Disable Spring Boot basic authentication
  basic:
    enabled: false
  oauth2:
    sso:
      loginPath: /login
    client:
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      clientAuthenticationScheme: form
      #setze in Docker Container über docker run ... -e CLIENTID= ...
      #setze in Eclipse über Environment Variables in Run Config
      clientId: ${CLIENTID}
      clientSecret: ${CLIENTSECRET}
      
      #funktioniert nicht: RedirectUri auf Github geändert
      #pre-established-redirect-uri: http://localhost:9090/birthdays/get
    resource:
      userInfoUri: https://api.github.com/user

    #resource:
    #  jwt:
    #    keyValue: |
    #      -----BEGIN PUBLIC KEY-----
    #      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
    #      -----END PUBLIC KEY-----
    #  id: openid
    #  serviceId: ${PREFIX:}resource

proxy:
  auth:
    routes:
      birthdays: oauth2
      
logging:
  level.org.springframework.security: DEBUG